name: Diag
"on":
  issue_comment:
    types: [created]
jobs:
  j:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body, '/confirm') && contains(github.event.comment.body, '/ok') }}
    steps:
      - run: echo ok
