name: T1perm
"on":
  issue_comment:
    types: [created]
permissions:
  contents: write
  issues: write
jobs:
  j:
    runs-on: ubuntu-latest
    steps:
      - name: 校验权限
        run: |
          echo hi
          echo bye
